> `TF 2.0 supports eager execution so don't explicitly create a session and run the code in it, instead you it the conventional way`

In [1]:
import tensorflow as tf
import numpy as np

- **```constants```**

In [2]:
a = tf.constant([[3, 2], [8, 6]], tf.int16)

In [3]:
b = tf.constant([[4, 8], [3, 7]], tf.int16)

In [4]:
c = a*b
c

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[12, 16],
       [24, 42]], dtype=int16)>

In [5]:
# or
c.numpy()

array([[12, 16],
       [24, 42]], dtype=int16)

In [6]:
c = tf.multiply(a, b)
c.numpy()

array([[12, 16],
       [24, 42]], dtype=int16)

- **```zeros and ones```**

In [7]:
zero_tensor = tf.zeros([3, 5])
zero_tensor.numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [8]:
one_tensor = tf.ones([4, 4])
one_tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [9]:
fill_tensor = tf.fill([2, 2, 3], 81.0)
fill_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[81., 81., 81.],
        [81., 81., 81.]],

       [[81., 81., 81.],
        [81., 81., 81.]]], dtype=float32)>

In [10]:
lin_tensor = tf.linspace(5., 9., 5)
lin_tensor.numpy()

array([5., 6., 7., 8., 9.], dtype=float32)

In [11]:
range_tensor = tf.range(3., 11., delta=0.5)
range_tensor.numpy()

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,
        8.5,  9. ,  9.5, 10. , 10.5], dtype=float32)

In [12]:
range_tensor = tf.range(3., 7., delta=0.5)
range_tensor.numpy()

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

- **```Tensors with Random Values```**

In [13]:
rnd_ints = tf.random.normal([10], dtype=tf.float64)
range_tensor.numpy()

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

In [14]:
rnd_ints = tf.random.uniform([10], dtype=tf.float64)
rnd_ints  # shuffle

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.54953107, 0.55722714, 0.35577241, 0.4806623 , 0.14036278,
       0.57389899, 0.78936421, 0.47520882, 0.70379277, 0.16137265])>

- **```Transforming Tensors```**

In [15]:
vec = tf.constant([1., 2., 3., 4.])
mat = tf.reshape(vec, [2, 2])
mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [16]:
mat = tf.constant([[1., 2., 3.], [4., 5., 6.]])
rev_mat = tf.reverse(mat, [1])  # 0 is across x axis i.e rows
# 1 is across y axis i.e columns
rev_mat

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 2., 1.],
       [6., 5., 4.]], dtype=float32)>

In [17]:
mat = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
# works same as select and drag(and leave)
slice_mat = tf.slice(mat, [1, 1], [2, 2])
slice_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 6.],
       [8., 9.]], dtype=float32)>

In [18]:
t1 = tf.constant([1., 2.])
t2 = tf.constant([3., 4.])
t3 = tf.constant([5., 6.])
t4 = tf.stack([t1, t2, t3])
t4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

 -                                          **```Operations```**

 | Function | Description |
 |   ---     |       ---    |
 | add(x, y, name=None)     |  Adds two tensors                     |  
 | subtract(x, y, name=None)|  Subtracts two tensors                |  
 | multiply(x, y, name=None)|  Multiplies two tensors               |  
 | divide(x, y, name=None)  |  Divides the elements of two tensors  |  
 | div(x, y, name=None)     |  Divides the elements of two tensors  |  
 | add_n(inputs, name=None) |  Adds multiple tensors                |  
 | scalar_mul(scalar, x)    |  Scales a tensor by a scalar value    |
 | mod(x, y, name=None)     |  Performs the modulo operation        |  
 | abs(x, name=None)        |  Computes the absolute value          |  
 | negative(x, name=None)   |  Negates the tensor’s elements        |  
 | sign(x, name=None)       |  Extracts the signs of the tensor’s element |  
 | reciprocal(x, name=None) |  Computes the reciprocals             |  

In [19]:
a = tf.constant([3., 3., 3.])
b = tf.constant([2., 2., 2.])
sum = tf.add(a, b)
diff = tf.subtract(a, b)
prod = tf.multiply(a, b)
quot = tf.divide(a, b)

print(sum.numpy(), diff.numpy(), prod.numpy(), quot.numpy())

[5. 5. 5.] [1. 1. 1.] [6. 6. 6.] [1.5 1.5 1.5]


In [20]:
# combining all the above

# Math with constant tensors
const_a = tf.constant(3.6)
const_b = tf.constant(1.2)
total = const_a + const_b
quot = tf.math.divide(const_a, const_b)

# Math with random tensors
rand_a = tf.random.normal([3], 2.0)
rand_b = tf.random.uniform([3], 1.0, 4.0)
diff = tf.subtract(rand_a, rand_b)


# Vector multiplication
vec_a = tf.linspace(0.0, 3.0, 4)
vec_b = tf.fill([4, 1], 2.0)
prod = tf.multiply(vec_a, vec_b)
dot = tf.tensordot(vec_a, vec_b, 1)

# Matrix multiplication
mat_a = tf.constant([[2, 3], [1, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 1], [3, 7, 2]])
mat_prod = tf.matmul(mat_a, mat_b)


# Execute the operations
print("Sum: %f" % (total))
print("Quotient: %f" % (quot))
print("Difference: ", (diff))
print("Element-wise product: ", (prod))
print("Dot product: ", (dot))
print("Matrix product: ", (mat_prod))

Sum: 4.800000
Quotient: 3.000000
Difference:  tf.Tensor([-0.15130281  1.2907026  -0.8662355 ], shape=(3,), dtype=float32)
Element-wise product:  tf.Tensor(
[[0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]], shape=(4, 4), dtype=float32)
Dot product:  tf.Tensor([12.], shape=(1,), dtype=float32)
Matrix product:  tf.Tensor(
[[21 29  8]
 [12 18  5]
 [39 51 14]], shape=(3, 3), dtype=int32)


In [21]:
tf.summary

<module 'tensorboard.summary._tf.summary' from 'C:\\Users\\KIRAN\\anaconda3\\lib\\site-packages\\tensorboard\\summary\\_tf\\summary\\__init__.py'>